import React from "react";
import { createRoot } from "react-dom/client";
import "@fontsource/noto-serif-jp/400.css";
import "@fontsource/noto-serif-jp/700.css";
import "@fontsource/noto-sans-jp/400.css";
import "@fontsource/noto-sans-jp/500.css";
import "@fontsource/zen-maru-gothic/400.css";
import "@fontsource/zen-maru-gothic/500.css";
import "@fontsource/zen-maru-gothic/700.css";
import "./style.css";
import "./refinements.css";
import "./teak.css";
import App from "./App.jsx";
createRoot(document.getElementById("root")).render(<App />);
